name: GitHub Actions

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Java (هنا اختار الإصدار اللي بتستخدمه)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Build and test
      - name: Build and run tests
        run: mvn -B clean test

      # Show test results
      - name: Display test results
        if: always()
        run: cat target/surefire-reports/*.txt || echo "No test reports found"
